version: '2.3'

services:
  ui_app:
    build:
      context: .
      target: 'bicing_ui_app_dev'
    networks: ['app']
    ports: ['3000:3000']
    volumes: ['.:/usr/src/app', './node_modules:/usr/src/app/node_modules']

  bicingapi-mock:
    image: 'fabriciomendonca/json-server-https'
    networks: ['app']
    ports: ['8443:8000']
    volumes: ['./docker/stages/development/mock/custom:/data/custom', './docker/stages/development/mock/server.js:/data/server.js']

networks:
  app:
