version: '2.3'

services:
  node:
    build:
      context: .
      target: 'bicing_app_node_dev'
    networks: ['app']
    ports: ['3000:3000']
    volumes: ['.:/usr/src/app', './node_modules:/usr/src/app/node_modules']

  bicinapi-mock:
    image: 'fabriciomendonca/json-server-https'
    networks: ['app']
    ports: ['8443:8000']
    volumes: ['./docker/stages/development/mock/custom:/data/custom', './docker/stages/development/mock/server.js:/data/server.js']

  # test-feature:
  #   build: './docker/chrome'
  #   cap_add: [SYS_ADMIN]
  #   networks: ['app']
  #   ports: ['9222:9222']
  #   shm_size: '1gb'

networks:
  app:
